// <auto-generated />
using System;
using HappyFarmer.AuthService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyFarmer.AuthService.Api.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260716004739_AddProvinces")]
    partial class AddProvinces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappyFarmer.AuthService.Api.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bà Rịa - Vũng Tàu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bình Dương"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bình Định"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bình Phước"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Đắk Nông"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hà Nam"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Hậu Giang"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Kiên Giang"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Long An"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ninh Thuận"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Phú Yên"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Quảng Bình"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Quảng Nam"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Tiền Giang"
                        },
                        new
                        {
                            Id = 58,
                            Name = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Vĩnh Phúc"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Yên Bái"
                        });
                });

            modelBuilder.Entity("HappyFarmer.AuthService.Api.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HappyFarmer.AuthService.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HappyFarmer.AuthService.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("HappyFarmer.AuthService.Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyFarmer.AuthService.Api.Entities.User", b =>
                {
                    b.HasOne("HappyFarmer.AuthService.Api.Entities.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HappyFarmer.AuthService.Api.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
