// <auto-generated />
using System;
using HappyFarmer.MarketPriceService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyFarmer.MarketPriceService.Api.Migrations
{
    [DbContext(typeof(MarketPriceDbContext))]
    [Migration("20260703033742_SeedCrawlerCatalog")]
    partial class SeedCrawlerCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappyFarmer.MarketPriceService.Api.Entities.PriceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("ProductId", "RegionId", "Status", "EffectiveDate");

                    b.ToTable("PriceEntries");
                });

            modelBuilder.Entity("HappyFarmer.MarketPriceService.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "Rau củ quả",
                            NameVi = "Xà lách",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Rau củ quả",
                            NameVi = "Rau diếp cá",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Rau củ quả",
                            NameVi = "Cải ngọt",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Rau củ quả",
                            NameVi = "Cải bẹ xanh",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Rau củ quả",
                            NameVi = "Rau muống",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 106,
                            Category = "Rau củ quả",
                            NameVi = "Bí đao",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 107,
                            Category = "Rau củ quả",
                            NameVi = "Dưa leo",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 108,
                            Category = "Rau củ quả",
                            NameVi = "Hành lá",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 109,
                            Category = "Rau củ quả",
                            NameVi = "Nấm rơm",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 110,
                            Category = "Rau củ quả",
                            NameVi = "Đậu bắp",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 111,
                            Category = "Nông sản công nghiệp",
                            NameVi = "Hồ tiêu",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 112,
                            Category = "Nông sản công nghiệp",
                            NameVi = "Cà phê",
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("HappyFarmer.MarketPriceService.Api.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            MarketName = "Chợ Vĩnh Long",
                            ProvinceName = "Vĩnh Long"
                        },
                        new
                        {
                            Id = 102,
                            MarketName = "Chợ đầu mối (tổng hợp)",
                            ProvinceName = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 103,
                            MarketName = "Giá tham khảo tỉnh",
                            ProvinceName = "Gia Lai"
                        },
                        new
                        {
                            Id = 104,
                            MarketName = "Giá tham khảo tỉnh",
                            ProvinceName = "Đồng Nai"
                        },
                        new
                        {
                            Id = 105,
                            MarketName = "Giá tham khảo tỉnh",
                            ProvinceName = "Đắk Nông"
                        },
                        new
                        {
                            Id = 106,
                            MarketName = "Giá tham khảo tỉnh",
                            ProvinceName = "Đắk Lắk"
                        },
                        new
                        {
                            Id = 107,
                            MarketName = "Giá tham khảo tỉnh",
                            ProvinceName = "Lâm Đồng"
                        });
                });

            modelBuilder.Entity("HappyFarmer.MarketPriceService.Api.Entities.PriceEntry", b =>
                {
                    b.HasOne("HappyFarmer.MarketPriceService.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyFarmer.MarketPriceService.Api.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
